dist: trusty
sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "lts/*"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.0.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - "yarn install"
script:
  - "NODE_PATH=. yarn lint"


